<?php

function elasticsearch_init(){
  $libraries = libraries_get_libraries();
   if (isset($libraries['Elastica'])) {
     $elastica_path = libraries_get_path('Elastica') . DIRECTORY_SEPARATOR . 'lib';
     set_include_path(get_include_path() . PATH_SEPARATOR . DRUPAL_ROOT . DIRECTORY_SEPARATOR . $elastica_path);
     set_include_path(get_include_path() . PATH_SEPARATOR . realpath(dirname(__FILE__) . '/../lib'));

     spl_autoload_register('elasticsearch_autoload');

     $client = new Elastica_Client();
  }
}

function elasticsearch_autoload($class) {
  if (substr($class, 0, 9) == 'Elastica_') {
    $file = str_replace('_', '/', $class) . '.php';
    require_once $file;
  }
}
